### ISSUE TITLE
Add Github workflow to auto push docker image to Github Container Registry

### ISSUE THREAD

**Issue by ZachGarcia42** [cornellrocketryteam/Ground-Software#15]
We should probably setup a Rocketry docker hub account. I currently just pushed an image to a personal account I made: https://hub.docker.com/u/zachgarcia42. Then we can follow this to auto push: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

**Comment by maxslarsson** [comment]
I think instead of setting up a Rocketry docker hub, we can just push to Github Container Registry. That means the image gets tied to this repo, and can be made from a Github action. Also means we dont have to create an account.
